---
# defaults file for ssh_key_local
ssh_key_state: present
ssh_key_directory: ~/.ssh
ssh_key_name: id_rsa
ssh_key_type: rsa # [rsa â† (default), dsa, rsa1, ecdsa, ed25519 ]
ssh_key_size: 2048
ssh_key_private_file: "{{ ssh_key_directory }}/{{ ssh_key_name }}"
ssh_key_public_file: "{{ ssh_key_directory }}/{{ ssh_key_name }}.pub"
